/* VidyaDesk fee engine. Uses the V2 schema and is intentionally deterministic. */
window.VidyaFeeEngine=(()=>{
 const iso=d=>new Date(d).toISOString().slice(0,10);
 const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return iso(x)};
 const addMonths=(d,n)=>{const x=new Date(d);x.setMonth(x.getMonth()+n);return iso(x)};
 function proRata(amount,joinDate,periodStart){const j=new Date(joinDate),s=new Date(periodStart);if(j<=s)return Number(amount);const days=new Date(s.getFullYear(),s.getMonth()+1,0).getDate();const remaining=days-j.getDate()+1;return Math.round(Number(amount)*remaining/days*100)/100}
 function periods(basis,joinDate,endDate){const out=[];let cur=new Date(joinDate),end=endDate?new Date(endDate):new Date(cur.getFullYear()+5,cur.getMonth(),cur.getDate());let guard=0;while(cur<end&&guard++<120){let next;if(basis==='monthly')next=new Date(cur.getFullYear(),cur.getMonth()+1,cur.getDate());else if(basis==='quarterly')next=new Date(cur.getFullYear(),cur.getMonth()+3,cur.getDate());else if(basis==='half_yearly')next=new Date(cur.getFullYear(),cur.getMonth()+6,cur.getDate());else if(basis==='yearly')next=new Date(cur.getFullYear()+1,cur.getMonth(),cur.getDate());else break;out.push({start:iso(cur),end:iso(new Date(next.getTime()-86400000))});cur=next}return out}
 function billsForEnrollment(e,plan,from,to){if(!plan||e.status!=='active')return[];const basis=plan.basis;const start=new Date(from||e.join_date),stop=new Date(to||e.end_date||addMonths(start,1));if(basis==='course'){const total=Math.max(0,Number(plan.amount)-Number(e.discount_amount||0));const count=Math.max(1,Number(plan.installments_count||1));return Array.from({length:count},(_,i)=>({period_start:iso(start),period_end:iso(stop),gross_amount:Math.round(Number(plan.amount)/count*100)/100,discount_amount:i===0?Number(e.discount_amount||0):0,due_date:addDays(iso(start),i*30)}))}return periods(basis,e.join_date,e.end_date||to).map((p,i)=>({period_start:p.start,period_end:p.end,gross_amount:(i===0&&basis==='monthly')?proRata(plan.amount,e.join_date,p.start):Number(plan.amount),discount_amount:i===0?Number(e.discount_amount||0):0,due_date:p.start}));}
 function nextBillNumber(prefix,sequence){return `${prefix||'VD'}-${new Date().getFullYear()}-${String(sequence||1).padStart(5,'0')}`}
 return {iso,addDays,addMonths,proRata,periods,billsForEnrollment,nextBillNumber};
})();