-- VidyaDesk corrected schema generated from the supplied supabase_schema.sql.
-- The application table definitions are preserved; only the generic RLS section is corrected.
-- Run supabase_fresh_reset.sql first, then this complete file.

begin;
create extension if not exists pgcrypto;

create table if not exists public.institutes (id uuid primary key default gen_random_uuid(), name text not null, logo_url text, owner_name text, phone text, whatsapp text, email text, address text, city text, state text, pincode text, website text, institute_type text not null default 'hybrid', academic_year text, gst_enabled boolean not null default false, gstin text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.institute_settings (institute_id uuid primary key references public.institutes(id) on delete cascade, currency text not null default 'INR', fee_cycle text not null default 'monthly', pro_rata_mode text not null default '30_day', reminder_day_1 int default 5, reminder_day_2 int default 10, dark_mode boolean not null default false, app_lock_enabled boolean not null default false, app_lock_pin_hash text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.institute_accounts (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, name text not null, account_type text not null check(account_type in ('cash','bank','upi','other')), bank_name text, account_number_masked text, ifsc text, opening_balance numeric(14,2) not null default 0, current_balance numeric(14,2) not null default 0, status text not null default 'active', created_at timestamptz not null default now());
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, institute_id uuid references public.institutes(id) on delete cascade, role text not null default 'student' check(role in ('owner','admin','teacher','employee','student','parent')), full_name text not null, email text, mobile text, avatar_url text, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.families (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, guardian_name text, guardian_mobile text, guardian_email text, address text, created_at timestamptz not null default now(), unique(institute_id, guardian_mobile));
create table if not exists public.family_members (family_id uuid not null references public.families(id) on delete cascade, student_id uuid not null, relationship text, primary key(family_id, student_id));
create table if not exists public.teachers (id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id) on delete set null, institute_id uuid not null references public.institutes(id) on delete cascade, full_name text not null, employee_code text, mobile text, email text, qualification text, subject text, address text, joining_date date, salary numeric(14,2) not null default 0, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.employees (id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id) on delete set null, institute_id uuid not null references public.institutes(id) on delete cascade, employee_code text, full_name text not null, mobile text, email text, role_title text, department text, joining_date date, salary numeric(14,2) not null default 0, bank_details jsonb not null default '{}'::jsonb, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.students (id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id) on delete set null, institute_id uuid not null references public.institutes(id) on delete cascade, family_id uuid references public.families(id) on delete set null, student_code text, full_name text not null, father_name text, mother_name text, guardian_name text, mobile text, alternate_mobile text, email text, dob date, gender text, blood_group text, address text, school text, class_name text, board text, join_date date not null default current_date, leaving_date date, status text not null default 'active' check(status in ('active','inactive','completed','left','transferred')), photo_url text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.student_documents (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, document_type text not null, file_path text not null, file_name text, created_at timestamptz not null default now());
create table if not exists public.batches (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, name text not null, code text, organization_style text not null default 'class_wise' check(organization_style in ('class_wise','subject_wise','competitive')), class_name text, subject text, course_name text, duration text, teacher_id uuid references public.teachers(id) on delete set null, room text, capacity int, start_date date, end_date date, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.fee_plans (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, batch_id uuid references public.batches(id) on delete cascade, name text not null, basis text not null check(basis in ('monthly','quarterly','half_yearly','yearly','course')), amount numeric(14,2) not null default 0, installments_count int not null default 1, due_day int default 5, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.batch_enrollments (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, batch_id uuid not null references public.batches(id) on delete cascade, fee_plan_id uuid references public.fee_plans(id) on delete set null, discount_amount numeric(14,2) not null default 0, join_date date not null default current_date, end_date date, status text not null default 'active', created_at timestamptz not null default now(), unique(student_id,batch_id));
create table if not exists public.fee_bills (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, student_id uuid not null references public.students(id) on delete restrict, enrollment_id uuid references public.batch_enrollments(id) on delete set null, batch_id uuid references public.batches(id) on delete set null, fee_plan_id uuid references public.fee_plans(id) on delete set null, bill_number text not null, description text not null, period_start date, period_end date, due_date date, gross_amount numeric(14,2) not null default 0, discount_amount numeric(14,2) not null default 0, net_amount numeric(14,2) generated always as (gross_amount-discount_amount) stored, status text not null default 'pending' check(status in ('pending','partial','paid','void')), created_at timestamptz not null default now(), unique(institute_id,bill_number));
create table if not exists public.fee_items (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, bill_id uuid not null references public.fee_bills(id) on delete cascade, description text not null, amount numeric(14,2) not null default 0, created_at timestamptz not null default now());
create table if not exists public.fee_discounts (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, bill_id uuid not null references public.fee_bills(id) on delete cascade, discount_type text not null, amount numeric(14,2) not null, reason text, approved_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.fee_installments (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, bill_id uuid not null references public.fee_bills(id) on delete cascade, installment_no int not null, due_date date, amount numeric(14,2) not null, paid_amount numeric(14,2) not null default 0, status text not null default 'pending', unique(bill_id,installment_no));
create table if not exists public.fee_payments (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, bill_id uuid not null references public.fee_bills(id) on delete restrict, account_id uuid references public.institute_accounts(id) on delete set null, amount numeric(14,2) not null check(amount>0), payment_mode text not null default 'cash', reference_no text, paid_at timestamptz not null default now(), received_by uuid references public.profiles(id) on delete set null, status text not null default 'posted', notes text, created_at timestamptz not null default now());
create table if not exists public.fee_receipts (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, payment_id uuid not null references public.fee_payments(id) on delete restrict, receipt_no text not null, pdf_path text, created_at timestamptz not null default now(), unique(institute_id,receipt_no));
create table if not exists public.attendance (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, batch_id uuid references public.batches(id) on delete set null, attendance_date date not null, status text not null check(status in ('present','absent','late','leave')), marked_by uuid references public.profiles(id) on delete set null, source text not null default 'manual', punch_time timestamptz, note text, created_at timestamptz not null default now(), unique(student_id,attendance_date));
create table if not exists public.attendance_devices (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, name text not null, vendor text, ip_address text, port int, device_id text, status text not null default 'offline', last_sync_at timestamptz, config jsonb not null default '{}'::jsonb);
create table if not exists public.attendance_logs (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, device_id uuid references public.attendance_devices(id) on delete set null, external_user_id text, punch_time timestamptz not null, raw_payload jsonb not null default '{}'::jsonb, processed boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.homework (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, batch_id uuid references public.batches(id) on delete set null, title text not null, description text, due_date date, attachment_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.diary_entries (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, teacher_id uuid references public.teachers(id) on delete set null, batch_id uuid references public.batches(id) on delete set null, entry_date date not null default current_date, title text, body text, attachment_path text, created_at timestamptz not null default now());
create table if not exists public.study_materials (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, batch_id uuid references public.batches(id) on delete set null, subject text, title text not null, material_type text not null default 'pdf', url text, storage_path text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.notices (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, title text not null, body text not null, audience text not null default 'all', publish_at timestamptz default now(), created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.courses (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, title text not null, description text, cover_path text, status text not null default 'draft', created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.course_sections (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, title text not null, position int not null default 0);
create table if not exists public.course_lessons (id uuid primary key default gen_random_uuid(), section_id uuid not null references public.course_sections(id) on delete cascade, title text not null, lesson_type text not null default 'video', video_url text, pdf_path text, body text, position int not null default 0);
create table if not exists public.course_enrollments (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, course_id uuid not null references public.courses(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, created_at timestamptz not null default now(), unique(course_id,student_id));
create table if not exists public.course_progress (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.course_lessons(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, completed boolean not null default false, progress_percent numeric(5,2) not null default 0, last_position_seconds int not null default 0, updated_at timestamptz not null default now(), unique(lesson_id,student_id));
create table if not exists public.course_notes (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.course_lessons(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, note text not null, created_at timestamptz not null default now());
create table if not exists public.course_bookmarks (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.course_lessons(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, created_at timestamptz not null default now(), unique(lesson_id,student_id));
create table if not exists public.course_discussions (id uuid primary key default gen_random_uuid(), lesson_id uuid not null references public.course_lessons(id) on delete cascade, author_id uuid not null references public.profiles(id) on delete cascade, body text not null, created_at timestamptz not null default now());
create table if not exists public.exams (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, title text not null, description text, batch_id uuid references public.batches(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, exam_date date, total_marks numeric(12,2) not null default 0, duration_minutes int, status text not null default 'draft', created_at timestamptz not null default now());
create table if not exists public.exam_questions (id uuid primary key default gen_random_uuid(), exam_id uuid not null references public.exams(id) on delete cascade, question_text text not null, option_a text, option_b text, option_c text, option_d text, correct_option text, marks numeric(10,2) not null default 1, position int not null default 0);
create table if not exists public.exam_attempts (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, started_at timestamptz, submitted_at timestamptz, score numeric(12,2) default 0, status text not null default 'started', unique(exam_id,student_id));
create table if not exists public.exam_answers (id uuid primary key default gen_random_uuid(), attempt_id uuid not null references public.exam_attempts(id) on delete cascade, question_id uuid not null references public.exam_questions(id) on delete cascade, selected_option text, is_correct boolean, marks_awarded numeric(12,2) default 0, unique(attempt_id,question_id));
create table if not exists public.exam_marks (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, marks numeric(12,2) not null default 0, grade text, remarks text, created_at timestamptz not null default now(), unique(exam_id,student_id));
create table if not exists public.results (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, exam_id uuid not null references public.exams(id) on delete cascade, student_id uuid not null references public.students(id) on delete cascade, percentage numeric(6,2), grade text, result_status text, pdf_path text, created_at timestamptz not null default now(), unique(exam_id,student_id));
create table if not exists public.timetables (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, batch_id uuid references public.batches(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, weekday int not null, start_time time not null, end_time time not null, room text, subject text, created_at timestamptz not null default now());
create table if not exists public.leads (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, name text not null, guardian_name text, mobile text, email text, source text, course_interest text, status text not null default 'new', assigned_to uuid references public.profiles(id) on delete set null, next_followup date, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.lead_followups (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, lead_id uuid not null references public.leads(id) on delete cascade, followup_date date not null, notes text, status text not null default 'pending', created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.expense_categories (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, name text not null, created_at timestamptz not null default now(), unique(institute_id,name));
create table if not exists public.expenses (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, category_id uuid references public.expense_categories(id) on delete set null, amount numeric(14,2) not null, expense_date date not null default current_date, description text, payment_mode text default 'cash', created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.payroll (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, employee_id uuid references public.employees(id) on delete set null, teacher_id uuid references public.teachers(id) on delete set null, salary_month date not null, salary_amount numeric(14,2) not null, paid_amount numeric(14,2) not null default 0, payment_date date, payment_mode text, status text not null default 'pending', payslip_path text, created_at timestamptz not null default now());
create table if not exists public.leave_requests (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, employee_id uuid references public.employees(id) on delete cascade, profile_id uuid references public.profiles(id) on delete cascade, from_date date not null, to_date date not null, reason text, status text not null default 'pending', approved_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());
create table if not exists public.user_permissions (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, permission text not null, allowed boolean not null default true, created_at timestamptz not null default now(), unique(user_id,permission));
create table if not exists public.batch_permissions (user_id uuid not null references public.profiles(id) on delete cascade, batch_id uuid not null references public.batches(id) on delete cascade, primary key(user_id,batch_id));
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, recipient_id uuid references public.profiles(id) on delete cascade, title text not null, body text not null, channel text not null default 'in_app', status text not null default 'pending', sent_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.notification_logs (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, recipient_id uuid references public.profiles(id) on delete set null, channel text not null, event_type text, payload jsonb not null default '{}'::jsonb, status text not null default 'queued', provider_message_id text, error_message text, created_at timestamptz not null default now());
create table if not exists public.activity_logs (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, action text not null, table_name text, record_id uuid, old_data jsonb, new_data jsonb, created_at timestamptz not null default now());
create table if not exists public.backup_records (id uuid primary key default gen_random_uuid(), institute_id uuid not null references public.institutes(id) on delete cascade, backup_type text not null default 'manual', storage_path text, created_by uuid references public.profiles(id) on delete set null, created_at timestamptz not null default now());

-- RLS: enable all application tables.
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['institutes','institute_settings','institute_accounts','profiles','families','family_members','teachers','employees','students','student_documents','batches','fee_plans','batch_enrollments','fee_bills','fee_items','fee_discounts','fee_installments','fee_payments','fee_receipts','attendance','attendance_devices','attendance_logs','homework','diary_entries','study_materials','notices','courses','course_sections','course_lessons','course_enrollments','course_progress','course_notes','course_bookmarks','course_discussions','exams','exam_questions','exam_attempts','exam_answers','exam_marks','results','timetables','leads','lead_followups','expense_categories','expenses','payroll','leave_requests','user_permissions','batch_permissions','notifications','notification_logs','activity_logs','backup_records'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;

-- Generic policy ONLY for tables with a direct institute_id.
DO $$ DECLARE t text; BEGIN
  FOREACH t IN ARRAY ARRAY['institute_settings','institute_accounts','families','teachers','employees','students','student_documents','batches','fee_plans','batch_enrollments','fee_bills','fee_items','fee_discounts','fee_installments','fee_payments','fee_receipts','attendance','attendance_devices','attendance_logs','homework','diary_entries','study_materials','notices','courses','course_enrollments','exams','exam_attempts','exam_marks','results','timetables','leads','lead_followups','expense_categories','expenses','payroll','leave_requests','user_permissions','notifications','notification_logs','activity_logs','backup_records'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS vd_select ON public.%I',t);
    EXECUTE format('CREATE POLICY vd_select ON public.%I FOR SELECT USING (institute_id = public.vd_my_institute_id())',t);
    EXECUTE format('DROP POLICY IF EXISTS vd_owner_write ON public.%I',t);
    EXECUTE format('CREATE POLICY vd_owner_write ON public.%I FOR ALL USING (public.vd_is_owner() AND institute_id = public.vd_my_institute_id()) WITH CHECK (public.vd_is_owner() AND institute_id = public.vd_my_institute_id())',t);
  END LOOP;
END $$;

-- profiles
DROP POLICY IF EXISTS vd_profiles_select ON public.profiles;
CREATE POLICY vd_profiles_select ON public.profiles FOR SELECT USING (id=auth.uid() OR institute_id=public.vd_my_institute_id());
DROP POLICY IF EXISTS vd_profiles_owner ON public.profiles;
CREATE POLICY vd_profiles_owner ON public.profiles FOR ALL USING (public.vd_is_owner() AND institute_id=public.vd_my_institute_id()) WITH CHECK (public.vd_is_owner() AND institute_id=public.vd_my_institute_id());

-- institutes
DROP POLICY IF EXISTS vd_institutes_select ON public.institutes;
CREATE POLICY vd_institutes_select ON public.institutes FOR SELECT USING (id=public.vd_my_institute_id());
DROP POLICY IF EXISTS vd_institutes_owner ON public.institutes;
CREATE POLICY vd_institutes_owner ON public.institutes FOR ALL USING (public.vd_is_owner() AND id=public.vd_my_institute_id()) WITH CHECK (public.vd_is_owner() AND id=public.vd_my_institute_id());

-- family_members -> families
DROP POLICY IF EXISTS vd_family_members_select ON public.family_members;
CREATE POLICY vd_family_members_select ON public.family_members FOR SELECT USING (EXISTS (SELECT 1 FROM public.families f WHERE f.id=family_members.family_id AND f.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_family_members_owner ON public.family_members;
CREATE POLICY vd_family_members_owner ON public.family_members FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.families f WHERE f.id=family_members.family_id AND f.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.families f WHERE f.id=family_members.family_id AND f.institute_id=public.vd_my_institute_id()));

-- course_sections -> courses
DROP POLICY IF EXISTS vd_course_sections_select ON public.course_sections;
CREATE POLICY vd_course_sections_select ON public.course_sections FOR SELECT USING (EXISTS (SELECT 1 FROM public.courses c WHERE c.id=course_sections.course_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_sections_owner ON public.course_sections;
CREATE POLICY vd_course_sections_owner ON public.course_sections FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.courses c WHERE c.id=course_sections.course_id AND c.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.courses c WHERE c.id=course_sections.course_id AND c.institute_id=public.vd_my_institute_id()));

-- course_lessons -> sections -> courses
DROP POLICY IF EXISTS vd_course_lessons_select ON public.course_lessons;
CREATE POLICY vd_course_lessons_select ON public.course_lessons FOR SELECT USING (EXISTS (SELECT 1 FROM public.course_sections cs JOIN public.courses c ON c.id=cs.course_id WHERE cs.id=course_lessons.section_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_lessons_owner ON public.course_lessons;
CREATE POLICY vd_course_lessons_owner ON public.course_lessons FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_sections cs JOIN public.courses c ON c.id=cs.course_id WHERE cs.id=course_lessons.section_id AND c.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_sections cs JOIN public.courses c ON c.id=cs.course_id WHERE cs.id=course_lessons.section_id AND c.institute_id=public.vd_my_institute_id()));

-- course_progress / notes / bookmarks -> lessons -> sections -> courses
DROP POLICY IF EXISTS vd_course_progress_select ON public.course_progress;
CREATE POLICY vd_course_progress_select ON public.course_progress FOR SELECT USING (EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_progress.lesson_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_progress_owner ON public.course_progress;
CREATE POLICY vd_course_progress_owner ON public.course_progress FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_progress.lesson_id AND c.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_progress.lesson_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_notes_select ON public.course_notes;
CREATE POLICY vd_course_notes_select ON public.course_notes FOR SELECT USING (EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_notes.lesson_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_notes_owner ON public.course_notes;
CREATE POLICY vd_course_notes_owner ON public.course_notes FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_notes.lesson_id AND c.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_notes.lesson_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_bookmarks_select ON public.course_bookmarks;
CREATE POLICY vd_course_bookmarks_select ON public.course_bookmarks FOR SELECT USING (EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_bookmarks.lesson_id AND c.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_bookmarks_owner ON public.course_bookmarks;
CREATE POLICY vd_course_bookmarks_owner ON public.course_bookmarks FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_bookmarks.lesson_id AND c.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.course_lessons cl JOIN public.course_sections cs ON cs.id=cl.section_id JOIN public.courses c ON c.id=cs.course_id WHERE cl.id=course_bookmarks.lesson_id AND c.institute_id=public.vd_my_institute_id()));

-- course_discussions -> author profile
DROP POLICY IF EXISTS vd_course_discussions_select ON public.course_discussions;
CREATE POLICY vd_course_discussions_select ON public.course_discussions FOR SELECT USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id=course_discussions.author_id AND p.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_course_discussions_owner ON public.course_discussions;
CREATE POLICY vd_course_discussions_owner ON public.course_discussions FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id=course_discussions.author_id AND p.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.profiles p WHERE p.id=course_discussions.author_id AND p.institute_id=public.vd_my_institute_id()));

-- exam_questions -> exams
DROP POLICY IF EXISTS vd_exam_questions_select ON public.exam_questions;
CREATE POLICY vd_exam_questions_select ON public.exam_questions FOR SELECT USING (EXISTS (SELECT 1 FROM public.exams e WHERE e.id=exam_questions.exam_id AND e.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_exam_questions_owner ON public.exam_questions;
CREATE POLICY vd_exam_questions_owner ON public.exam_questions FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.exams e WHERE e.id=exam_questions.exam_id AND e.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.exams e WHERE e.id=exam_questions.exam_id AND e.institute_id=public.vd_my_institute_id()));

-- exam_answers -> exam_attempts -> exams
DROP POLICY IF EXISTS vd_exam_answers_select ON public.exam_answers;
CREATE POLICY vd_exam_answers_select ON public.exam_answers FOR SELECT USING (EXISTS (SELECT 1 FROM public.exam_attempts a JOIN public.exams e ON e.id=a.exam_id WHERE a.id=exam_answers.attempt_id AND e.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_exam_answers_owner ON public.exam_answers;
CREATE POLICY vd_exam_answers_owner ON public.exam_answers FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.exam_attempts a JOIN public.exams e ON e.id=a.exam_id WHERE a.id=exam_answers.attempt_id AND e.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.exam_attempts a JOIN public.exams e ON e.id=a.exam_id WHERE a.id=exam_answers.attempt_id AND e.institute_id=public.vd_my_institute_id()));

-- batch_permissions -> batches
DROP POLICY IF EXISTS vd_batch_permissions_select ON public.batch_permissions;
CREATE POLICY vd_batch_permissions_select ON public.batch_permissions FOR SELECT USING (EXISTS (SELECT 1 FROM public.batches b WHERE b.id=batch_permissions.batch_id AND b.institute_id=public.vd_my_institute_id()));
DROP POLICY IF EXISTS vd_batch_permissions_owner ON public.batch_permissions;
CREATE POLICY vd_batch_permissions_owner ON public.batch_permissions FOR ALL USING (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.batches b WHERE b.id=batch_permissions.batch_id AND b.institute_id=public.vd_my_institute_id())) WITH CHECK (public.vd_is_owner() AND EXISTS (SELECT 1 FROM public.batches b WHERE b.id=batch_permissions.batch_id AND b.institute_id=public.vd_my_institute_id()));

commit;
